<html>
    <title> {{title}} </title>
    <header>
       
    </header>
    <body>

        hi {{sample}}
        <br/>
        <hr/>
       This is a dynamic content from model: {{modelData}} 
       <hr/>
       This is an array {{testArray}}
       <hr/>
       {{foreach arrayName as value}}
       {{/foreach}}
       <hr/>
       this is php: <?php $va="hello this generated by php"; echo $va; ?>
    </body>
    
</html>